=== just-the-docs/just-the-docs/schemas/1.0.0/cityjson.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "CityJSON v1.0.0",
  "description": "CityJSON specifications v1.0.0",
  "type": "object",

  "properties": {
    "type": { "enum": ["CityJSON"] },
    "version": { 
      "type": "string",
      "pattern": "^(\\d\\.)(\\d)$"
    },
    "metadata": {
      "type": "object",
      "$ref": "metadata.schema.json#/metadata"
    },
    "extensions": {
      "type": "object",
      "additionalProperties": { 
        "type": "object",
        "properties": {
          "url": { 
            "type": "string",  
            "format": "uri-reference"
          },
          "version": { 
            "type": "string",
            "pattern": "^(\\d\\.)(\\d)$"
          }  
        },
        "required": ["url", "version"]
      }
    },
    "CityObjects": {
      "type": "object",
      "additionalProperties": {
        "oneOf": [
          { "$ref": "cityobjects.schema.json#/CityObjectGroup" },
          { "$ref": "cityobjects.schema.json#/Building" },
          { "$ref": "cityobjects.schema.json#/BuildingPart" },
          { "$ref": "cityobjects.schema.json#/BuildingInstallation" },
          { "$ref": "cityobjects.schema.json#/Road" },
          { "$ref": "cityobjects.schema.json#/Railway" },
          { "$ref": "cityobjects.schema.json#/TransportSquare" },
          { "$ref": "cityobjects.schema.json#/TINRelief" },
          { "$ref": "cityobjects.schema.json#/WaterBody" },
          { "$ref": "cityobjects.schema.json#/LandUse" },
          { "$ref": "cityobjects.schema.json#/GenericCityObject" },
          { "$ref": "cityobjects.schema.json#/CityFurniture" },
          { "$ref": "cityobjects.schema.json#/SolitaryVegetationObject" },
          { "$ref": "cityobjects.schema.json#/PlantCover" },
          { "$ref": "cityobjects.schema.json#/Bridge" },
          { "$ref": "cityobjects.schema.json#/BridgePart" },
          { "$ref": "cityobjects.schema.json#/BridgeInstallation" },
          { "$ref": "cityobjects.schema.json#/BridgeConstructionElement" },
          { "$ref": "cityobjects.schema.json#/Tunnel" },
          { "$ref": "cityobjects.schema.json#/TunnelPart" },
          { "$ref": "cityobjects.schema.json#/TunnelInstallation" },
          { "$ref": "cityobjects.schema.json#/ExtensionObject" }
        ]
      }
    },
    "vertices": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {"type": "number"},
        "minItems": 3,    
        "maxItems": 3
      }
    },
    "transform": {
      "type": "object",
      "properties": {
        "scale": {
          "type": "array",
          "items": {"type": "number"},
          "minItems": 3,    
          "maxItems": 3
        },
        "translate": {
          "type": "array",
          "items": {"type": "number"},
          "minItems": 3,    
          "maxItems": 3
        }
      },
      "required": ["scale", "translate"],
      "additionalProperties": false
    },
    "appearance": {
      "type": "object",
      "properties": {
        "default-theme-texture": {"type": "string"},
        "default-theme-material": {"type": "string"},
        "materials": {
          "type": "array",
          "items": {"$ref": "appearance.schema.json#/Material"}
        },
        "textures": {
          "type": "array",
          "items": {"$ref": "appearance.schema.json#/Texture"}
        },
        "vertices-texture": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {"type": "number"},
            "minItems": 2,    
            "maxItems": 2
          }
        }
      },
      "additionalProperties": false
    },
    "geometry-templates": {
      "type": "object",
      "properties": {
        "templates": {
          "type": "array",
          "items": {
            "oneOf": [
              {"$ref": "geomprimitives.schema.json#/MultiPoint"},
              {"$ref": "geomprimitives.schema.json#/MultiLineString"},
              {"$ref": "geomprimitives.schema.json#/Solid"},
              {"$ref": "geomprimitives.schema.json#/MultiSolid"},
              {"$ref": "geomprimitives.schema.json#/CompositeSolid"},
              {"$ref": "geomprimitives.schema.json#/MultiSurface"},
              {"$ref": "geomprimitives.schema.json#/CompositeSurface"}            
            ] 
          }
        },
        "vertices-templates": {
          "type": "array",
          "items": {
            "type": "array",
            "items": { "type": "number" },
            "minItems": 3,    
            "maxItems": 3
          }
        }
      },
      "required": ["templates", "vertices-templates"],
      "additionalProperties": false
    }
  },
  "required": ["type", "version", "CityObjects", "vertices"]
}

=== just-the-docs/just-the-docs/tutorials/files/noise_data.city.json
{
  "type": "CityJSON",
  "version": "2.0",
  "extensions": {
    "Noise": {
      "url" : "https://www.cityjson.org/tutorials/files/noise.ext.json",
      "version": "1.1"
    }
  },
  "transform": {
    "scale": [0.0, 0.0, 0.0],
    "translate": [1.0, 1.0, 1.0]
  },  
  "CityObjects": {
    "1234": {
      "type": "Building",
      "geometry": [
        {
          "type": "Solid",
          "lod": "2",
          "boundaries": [
            [ [[0, 3, 2, 1]], [[4, 5, 6, 7]], [[0, 1, 5, 4]], [[1, 2, 6, 5]], [[2, 3, 7, 6]], [[3, 0, 4, 7]] ] 
          ]
        }
      ],
      "attributes": {
        "roofType": "pointy",
        "class": "22",
          "+noise-buildingReflectionCorrection": {
            "value": 4.123,
            "uom": "dB"
          },
          "+noise-buildingLNightMax": {
            "value": 43.123,
            "uom": "dB"
          }
      }
    },
    "thesegment_1": {
      "type": "+NoiseCityFurnitureSegment",
      "geometry": [
        {
          "type": "MultiLineString",
          "lod": "0",
          "boundaries": [
            [2, 3, 5], [7, 5, 12]
          ]
        }      
      ],
      "attributes": {
        "reflectionCorrection": {
          "value": 4.123,
          "uom": "dB"
        }
      },
      "parents": ["a_noisy_bench"]
    },    
    "thesegment_2": {
      "type": "+NoiseCityFurnitureSegment",
      "geometry": [
        {
          "type": "MultiLineString",
          "lod": "0",
          "boundaries": [ 
            [2, 3, 5], [7, 2, 12]
          ]
        }      
      ],
      "attributes": {
        "reflectionCorrection": {
          "value": 2.666,
          "uom": "dB"
        }
      },
      "parents": ["a_noisy_bench"]
    },    
    "a_noisy_bench": {
      "type": "CityFurniture",
      "geometry": [
        {
          "type": "Solid",
          "lod": "2",
          "boundaries": [
            [ [[0, 3, 2, 1]], [[4, 5, 6, 7]], [[0, 1, 5, 4]], [[1, 2, 6, 5]], [[2, 3, 7, 6]], [[3, 0, 4, 7]] ] 
          ]
        }
      ],
      "children": ["thesegment_1", "thesegment_2"]
    },
  	"onebuilding": {
      "type": "Building", 
      "geometry": [
      {
        "type": "Solid",
        "lod": "1",
        "boundaries": [
          [ [[0, 3, 2, 1]], [[4, 5, 6, 7]], [[0, 1, 5, 4]], [[1, 2, 6, 5]], [[2, 3, 7, 6]], [[3, 0, 4, 7]] ] 
        ]
      },
      {
        "type": "Solid",
        "lod": "2",
        "boundaries": [
          [ [[8, 11, 10, 9]], [[12, 13, 14, 15]], [[8, 9, 13, 12]], [[9, 10, 14, 13]], [[10, 11, 15, 14]], [[11, 8, 12, 15]] ] 
        ]
      }      
      ]        
    }  
  },
  "vertices": [
    [ 0,  0,  0],
    [10,  0,  1],
    [10, 10,  10],
    [ 0, 10,  0],
    [ 0,  0, 10],
    [10,  0, 10],
    [10, 11, 10],
    [ 0, 10, 10],
    [10,  0,  0],
    [20,  0,  0],
    [20, 10,  0],
    [10, 110,  0],
    [10,  0, 18],
    [20,  0, 14],
    [20, 10, 11],
    [10, 10, 11]
  ]
}
